version: "3.4"

services:
  api:
    container_name: check-ports-service
    image: ghcr.io/dappnode/check-ports-service:latest
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3030:3000
    restart: always
